//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actlog
    {
        public int id { get; set; }
        public Nullable<int> ownid { get; set; }
        public Nullable<int> userid { get; set; }
        public string cmd { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public Nullable<int> err { get; set; }
        public string entity { get; set; }
        public Nullable<int> entityid { get; set; }
    }
}
