//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alertsystemsadress
    {
        public int id { get; set; }
        public Nullable<int> alertsystemid { get; set; }
        public string account { get; set; }
        public string shipping { get; set; }
        public string billing { get; set; }
        public string billcontact { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> kind { get; set; }
    }
}
