//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alertcampaign
    {
        public int id { get; set; }
        public Nullable<int> eventid { get; set; }
        public Nullable<int> contactid { get; set; }
        public string phone { get; set; }
        public Nullable<int> nr { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> modtime { get; set; }
        public Nullable<int> calls { get; set; }
        public Nullable<int> deleted { get; set; }
        public string sname { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
    }
}
