//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill()
        {
            this.billrows = new HashSet<billrow>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public Nullable<int> alertsystemid { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> paid { get; set; }
        public string number { get; set; }
        public string account { get; set; }
        public string shipping { get; set; }
        public string billing { get; set; }
        public string billcontact { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string note { get; set; }
        public Nullable<int> kind { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billrow> billrows { get; set; }
    }
}
