//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int ownid { get; set; }
        public Nullable<int> keys { get; set; }
        public string name { get; set; }
        public Nullable<int> sentry { get; set; }
        public Nullable<decimal> deflat { get; set; }
        public Nullable<decimal> deflong { get; set; }
        public Nullable<int> rrate { get; set; }
        public Nullable<int> active { get; set; }
        public string prefix { get; set; }
        public string shipping { get; set; }
        public string billing { get; set; }
        public string contact_name { get; set; }
        public string contact_pos { get; set; }
        public string contact_phone { get; set; }
        public string contact_mobile { get; set; }
        public string contact_email { get; set; }
        public Nullable<int> mstype { get; set; }
        public Nullable<int> deleted { get; set; }
        public string billcontact { get; set; }
        public Nullable<int> fixedcount { get; set; }
        public Nullable<decimal> fixedprice { get; set; }
        public Nullable<decimal> extraprice { get; set; }
        public Nullable<int> tz { get; set; }
        public Nullable<int> tformat { get; set; }
        public Nullable<int> nopings { get; set; }
    }
}
