//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModels : DbContext
    {
        public DBModels()
            : base("name=DBModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_test> C_test { get; set; }
        public virtual DbSet<actlog> actlogs { get; set; }
        public virtual DbSet<alertcampaign> alertcampaigns { get; set; }
        public virtual DbSet<alertcontact> alertcontacts { get; set; }
        public virtual DbSet<alertprice> alertprices { get; set; }
        public virtual DbSet<alertstation> alertstations { get; set; }
        public virtual DbSet<alertsystem> alertsystems { get; set; }
        public virtual DbSet<alertsystemsadress> alertsystemsadresses { get; set; }
        public virtual DbSet<alertuser> alertusers { get; set; }
        public virtual DbSet<billrow> billrows { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<chargestation> chargestations { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<historylog> historylogs { get; set; }
        public virtual DbSet<ibutton> ibuttons { get; set; }
        public virtual DbSet<keyholder> keyholders { get; set; }
        public virtual DbSet<keystation> keystations { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<prop> props { get; set; }
        public virtual DbSet<raw> raws { get; set; }
        public virtual DbSet<sqllog> sqllogs { get; set; }
        public virtual DbSet<station> stations { get; set; }
        public virtual DbSet<tmp_ibuttons> tmp_ibuttons { get; set; }
        public virtual DbSet<tmp_keyholders> tmp_keyholders { get; set; }
        public virtual DbSet<tmp_list> tmp_list { get; set; }
        public virtual DbSet<tmp_warns> tmp_warns { get; set; }
        public virtual DbSet<tzone> tzones { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<tmp_alertcontacts> tmp_alertcontacts { get; set; }
        public virtual DbSet<tmp_treestations> tmp_treestations { get; set; }
        public virtual DbSet<tmp_users> tmp_users { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
