//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int id { get; set; }
        public Nullable<int> rawid { get; set; }
        public Nullable<int> ownid { get; set; }
        public Nullable<int> stationid { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<int> ibuttonid { get; set; }
        public Nullable<int> keyholderid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> charge { get; set; }
        public string edata { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public Nullable<int> response { get; set; }
        public Nullable<int> response_user { get; set; }
        public Nullable<System.DateTime> response_dt { get; set; }
        public Nullable<int> emailsent { get; set; }
        public Nullable<System.DateTimeOffset> eventdt { get; set; }
        public string note { get; set; }
        public Nullable<int> round { get; set; }
    }
}
