//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class station
    {
        public int id { get; set; }
        public Nullable<int> ownid { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> dstart { get; set; }
        public string esn { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<int> charge { get; set; }
        public Nullable<System.DateTime> dcharge { get; set; }
        public Nullable<int> eventid { get; set; }
        public Nullable<int> pricing { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<int> tz { get; set; }
        public Nullable<int> adminstatus { get; set; }
        public Nullable<int> tzone_id { get; set; }
        public Nullable<int> account_type { get; set; }
        public Nullable<int> paymentperiod { get; set; }
        public Nullable<bool> isnoping { get; set; }
    }
}
