//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_treestations
    {
        public int id { get; set; }
        public Nullable<int> ownid { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> dstart { get; set; }
        public string esn { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<int> charge { get; set; }
        public Nullable<System.DateTime> dcharge { get; set; }
        public Nullable<System.DateTime> devent { get; set; }
        public Nullable<int> alertsystemid { get; set; }
        public string alertname { get; set; }
        public Nullable<System.DateTime> event_dt { get; set; }
        public Nullable<int> event_status { get; set; }
        public string event_ibutton { get; set; }
        public string event_keyholder { get; set; }
        public Nullable<int> event_days { get; set; }
        public Nullable<int> pricing { get; set; }
        public string event_dt2 { get; set; }
        public Nullable<int> uniqueid { get; set; }
        public Nullable<int> parentid { get; set; }
    }
}
