//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_keyholders
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string phone { get; set; }
        public Nullable<int> ownid { get; set; }
        public Nullable<int> ibuttonid { get; set; }
        public string ibutton { get; set; }
        public Nullable<int> days { get; set; }
    }
}
