//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_warns
    {
        public Nullable<int> low { get; set; }
        public Nullable<int> noresp { get; set; }
        public int alert { get; set; }
        public Nullable<int> rrate { get; set; }
    }
}
