//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_ibuttons
    {
        public int id { get; set; }
        public string key { get; set; }
        public Nullable<int> ownid { get; set; }
        public Nullable<int> active { get; set; }
        public string name { get; set; }
        public Nullable<int> keyholderid { get; set; }
        public string crc { get; set; }
    }
}
