//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetPostgresEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> acclevel { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<int> active { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<int> ownid { get; set; }
        public string accword { get; set; }
        public Nullable<int> chgpassword { get; set; }
        public Nullable<int> alertcontactid { get; set; }
        public Nullable<int> otheruser { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<int> parentuser { get; set; }
        public Nullable<int> tzone_id { get; set; }
        public Nullable<int> tz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
